(define-module (lib sor-solver)
  #:export (sor-solve)
  #:use-module (lib staggered-grid))
(chdir "lib")
(system "make --quiet sor_solver.so")
(load-extension "./libsor_solver" "scm_init_sor_solver")
(chdir "..")

(define (sor-solve staggered-grid itermax eps)
  5)
